export const CLIENTS_COLUMNS = {
  LEAD_ALERT_FREQUENCY: "leadAlertsFrequency",
  BUSINESS_CITY: "businessCity",
  BUSINESS_INDUSTRY: "businessIndustry",
  PAYMENT_METHOD: "paymentMethod",
  LEAD_COST: "leadCost",
  BUYER_ID: "buyerId",
  CREDITS: "credits",
  LAST_NAME: "lastName",
  EMAIL: "email",
  FIRST_NAME: "firstName",
  BUSINESS_SALES_NUMBER: "businessSalesNumber",
  BUSINESS_ADDRESS: "businessAddress",
  BUSINESS_LOGO: "businessLogo",
  BUSINESS_POST_CODE: "businessPostCode",
  USER_SIGNUP_STATUS: "userSignupStatus",
  CREATED_AT: "createdAt",
  DAILY: "daily",
  ACCOUNT_MANAGER: "accountManager",
  PHONE_NUMBER: "phoneNumber",
};
