interface Country {
    mobilePrefixCode: number;
    label: string;
  }
  
  export const countries: Country[] = [
    { "mobilePrefixCode": 43, "label": "AUT" },
    { "mobilePrefixCode": 32, "label": "BEL" },
    { "mobilePrefixCode": 359, "label": "BGR" },
    { "mobilePrefixCode": 385, "label": "HRV" },
    { "mobilePrefixCode": 357, "label": "CYP" },
    { "mobilePrefixCode": 420, "label": "CZE" },
    { "mobilePrefixCode": 45, "label": "DNK" },
    { "mobilePrefixCode": 372, "label": "EST" },
    { "mobilePrefixCode": 358, "label": "FIN" },
    { "mobilePrefixCode": 33, "label": "FRA" },
    { "mobilePrefixCode": 49, "label": "DEU" },
    { "mobilePrefixCode": 30, "label": "GRC" },
    { "mobilePrefixCode": 36, "label": "HUN" },
    { "mobilePrefixCode": 353, "label": "IRL" },
    { "mobilePrefixCode": 39, "label": "ITA" },
    { "mobilePrefixCode": 371, "label": "LVA" },
    { "mobilePrefixCode": 370, "label": "LTU" },
    { "mobilePrefixCode": 352, "label": "LUX" },
    { "mobilePrefixCode": 356, "label": "MLT" },
    { "mobilePrefixCode": 31, "label": "NLD" },
    { "mobilePrefixCode": 48, "label": "POL" },
    { "mobilePrefixCode": 351, "label": "PRT" },
    { "mobilePrefixCode": 40, "label": "ROU" },
    { "mobilePrefixCode": 421, "label": "SVK" },
    { "mobilePrefixCode": 386, "label": "SVN" },
    { "mobilePrefixCode": 34, "label": "ESP" },
    { "mobilePrefixCode": 46, "label": "SWE" },
    { "mobilePrefixCode": 355, "label": "ALB" },
    { "mobilePrefixCode": 376, "label": "AND" },
    { "mobilePrefixCode": 374, "label": "ARM" },
    { "mobilePrefixCode": 375, "label": "BLR" },
    { "mobilePrefixCode": 387, "label": "BIH" },
    { "mobilePrefixCode": 298, "label": "FRO" },
    { "mobilePrefixCode": 995, "label": "GEO" },
    { "mobilePrefixCode": 350, "label": "GIB" },
    { "mobilePrefixCode": 354, "label": "ISL" },
    { "mobilePrefixCode": 44, "label": "IMN" },
    { "mobilePrefixCode": 381, "label": "XKX" },
    { "mobilePrefixCode": 423, "label": "LIE" },
    { "mobilePrefixCode": 389, "label": "MKD" },
    { "mobilePrefixCode": 373, "label": "MDA" },
    { "mobilePrefixCode": 377, "label": "MCO" },
    { "mobilePrefixCode": 382, "label": "MNE" },
    { "mobilePrefixCode": 47, "label": "NOR" },
    { "mobilePrefixCode": 7, "label": "RUS" },
    { "mobilePrefixCode": 378, "label": "SMR" },
    { "mobilePrefixCode": 381, "label": "SRB" },
    { "mobilePrefixCode": 41, "label": "CHE" },
    { "mobilePrefixCode": 90, "label": "TUR" },
    { "mobilePrefixCode": 380, "label": "UKR" },
    { "mobilePrefixCode": 44, "label": "GBR" },
    { "mobilePrefixCode": 39, "label": "VAT" },
    { "mobilePrefixCode": 1, "label": "USA" }
  ];
  
  