export const SENDGRID_STATUS_PERCENTAGE = {
    USER_SIGNUP_PERCENTAGE: '25',
    BUSINESS_INDUSTRY: 'Unknown',
    BUSINESS_DETAILS_PERCENTAGE: '50',
    LEAD_DETAILS_PERCENTAGE:'75',
    CARD_DETAILS_PERCENTAGE:'100'
  };
  