name: Deploy to Production

on:
  push:
    branches:
      - production

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SV_KEY_PASS: ${{ secrets.SV_KEY_PASS }}
  SV_IP_ADDRESS: ${{ secrets.SV_IP_ADDRESS }}
  SV_USER: ${{ secrets.SV_USER }}
  BUILD_DIR_PATH: ${{ vars.BUILD_DIR_PATH }}
  CI: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'production'

      - name: Install dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Package Build
        run: zip -r dist.zip {.,}*

      - name: Send Build to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SV_IP_ADDRESS }}
          username: ${{ env.SV_USER }}
          port: 22
          key: ${{ env.SSH_PRIVATE_KEY }}
          passphrase: ${{ env.SV_KEY_PASS }}
          source: "dist.zip"
          target: ${{ env.BUILD_DIR_PATH }}

      - name: Go Live
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ env.SV_IP_ADDRESS }}
          username: ${{ env.SV_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          passphrase: ${{ env.SV_KEY_PASS }}
          script: |
            cd ${{ env.BUILD_DIR_PATH }}
            unzip -o dist.zip
            pm2 restart all
            rm dist.zip
            rm -rf 'NarwhalLeads-Backend'
